#!/usr/bin/env bash
# Generated by Gradle Wrapper
APP_NAME="gradle"
APP_HOME="$(cd "$(dirname "$0")"; pwd)"
# Resolve symlinks, if any
if [ -L "$0" ]; then
  APP_HOME="$(cd "$(dirname "$(readlink "$0")")"; pwd)"
fi
exec "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"
